# Generated by Django 3.0.5 on 2020-06-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
                ('cost', models.FloatField()),
                ('category', models.CharField(choices=[('УЗИ', 'УЗИ'), ('ЭХОКАРДИОГРАФИЯ', 'ЭХОКАРДИОГРАФИЯ')], max_length=200, null=True)),
                ('additionalInfo', models.TextField()),
                ('current_visit', models.DateTimeField(auto_now_add=True)),
                ('next_visit', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
