# Generated by Django 3.0.5 on 2020-06-06 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0003_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='analys_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
